export const USDT = Object.freeze({
  ADA: 'ADA/USDT',
  ALGO: 'ALGO/USDT',
  APT: 'APT/USDT',
  ARB: 'ARB/USDT',
  BNB: 'BNB/USDT',
  BTC: 'BTC/USDT',
  DOGE: 'DOGE/USDT',
  DOT: 'DOT/USDT',
  ETH: 'ETH/USDT',
  HBAR: 'HBAR/USDT',
  LINK: 'LINK/USDT',
  LTC: 'LTC/USDT',
  MOVE: 'MOVE/USDT', // huobi is not tradable
  PENGU: 'PENGU/USDT',
  TON: 'TON/USDT',
  TRUMP: 'TRUMP/USDT',
  TRX: 'TRX/USDT',
  SOL: 'SOL/USDT',
  SUI: 'SUI/USDT',
  XLM: 'XLM/USDT',
  XRP: 'XRP/USDT',
  WLD: 'WLD/USDT',
});
